# MySQL配置项
mysql:
  host: 10.1.28.100
  port: 3306
  user: root
  password: Duwei4545945.o
  database: mysql
  charset: utf8mb4
  cursorclass: pymysql.cursors.DictCursor  # 返回字典格式的结果

# Hive配置项
hive:
  host: 10.1.28.100
  port: 10000
  username: root
  password:
  database: tdatabase
  auth: NOSASL
  configuration:

# HBase配置项
hbase:
  host: master

# HDFS配置项
hdfs:
  host: master